### ISSUE TITLE
new aesthetic?

### ISSUE THREAD

**Issue by futurepaul** [BitcoinDevShop/pln#25]
potential inspo:

gameboy
n64
retro desktop OS (but how to make it seem mobile?)

adjectives:
"nice"

**Comment by futurepaul** [comment]
![Image](https://user-images.githubusercontent.com/543668/178378462-1b52acb6-56f2-46c0-8a8c-df1abbdc2b86.png)

**Comment by TonyGiorgio** [comment]
![Screenshot from 2022-07-11 19-02-08](https://user-images.githubusercontent.com/101225832/178378524-b763cb70-a9e3-400b-9fb7-70458d22409e.png)

**Comment by futurepaul** [comment]
![201906289480cf50c65fd33ab_th_1024x0](https://user-images.githubusercontent.com/543668/178379016-9adb9f5e-7b00-4237-8b79-cb5dd60d7479.jpeg)
![static-assets-upload1919983930640460405 (1)](https://user-images.githubusercontent.com/543668/178379076-193768e1-dd90-4306-923c-978cd2683972.jpg)

**Comment by TonyGiorgio** [comment]
![e9d74fe4da2d6e282b99cfc723ee31c0--teenage-engineering-visual-effects](https://user-images.githubusercontent.com/101225832/178380886-db00e021-ddf3-4659-b81a-7653a28d51f8.jpg)


color scheme looks good

**Comment by futurepaul** [comment]
<img width="1183" alt="Screen Shot 2022-07-11 at 7 32 48 PM" src="https://user-images.githubusercontent.com/543668/178381328-54fa118d-99e0-4573-b7c3-d821f1ac78f5.png">

**Comment by TonyGiorgio** [comment]
![Screenshot from 2022-07-11 19-34-29](https://user-images.githubusercontent.com/101225832/178381429-c0b3f963-65b7-4842-8c43-2234023e0d65.png)
![Screenshot from 2022-07-11 19-32-45](https://user-images.githubusercontent.com/101225832/178381431-9d7d8e0b-47d2-4065-9ba4-914e3dd83366.png)

**Comment by TonyGiorgio** [comment]
![ob-128](https://user-images.githubusercontent.com/101225832/178382013-85518260-35b1-4ba8-9abc-38475783ab78.jpg)

**Comment by futurepaul** [comment]
closed by #63
