### ISSUE TITLE
scid alias stuff

### ISSUE THREAD

**Issue by futurepaul** [BitcoinDevShop/pln#29]

**Comment by benthecarman** [comment]
ldk supports this now

https://github.com/lightningdevkit/rust-lightning/pull/1311

**Comment by TonyGiorgio** [comment]
Mostly done, waiting on sensei: https://github.com/BitcoinDevShop/pln/pull/48

**Comment by TonyGiorgio** [comment]
merged, using scid_alias is done by default now but no warning if it has to fall back to not using an alias if the other node does not support it. The threat modeling API ticket should provide this warning and ask the user if they should proceed anyways.
