### ISSUE TITLE
threat trees for channel open and send payment

### ISSUE THREAD

**Issue by futurepaul** [BitcoinDevShop/pln#31]

**Comment by TonyGiorgio** [comment]
![Image](https://user-images.githubusercontent.com/101225832/179310477-296c7abd-797b-4c0f-b903-ddfec641a8e0.jpg)



The idea is that (possibly) every API can respond with a structured warning/action response that the frontend can trigger on and recommend solutions to the user. In the beginning, we are targeting channel open and send payment (the two main functions we are supporting). 

## Standard structure


```
  enum ThreatModelActionType {
    CANCEL = 0;
    PROCEED = 1;
    OPEN_CHANNEL_RANDOM = 2;
    OPEN_CHANNEL_HUB = 3;
  }

  enum ThreatModelActionFlag {
    GOOD = 0;
    WARNING = 1;
    BAD = 2;
  }

  message ThreatModelSolution {
    ThreatModelActionType type = 1; 
    ThreatModelActionFlag flag = 2; 
    string description = 3; 
  }

  message ThreatModelError {
    string description = 1; 
    repeated ThreatModelSolution solutions = 2; 
  }
```

## Channel Open Example

## Send Payment Example

**Comment by TonyGiorgio** [comment]
@futurepaul please take a look at the above and let me know if that sounds good and makes sense.

**Comment by TonyGiorgio** [comment]
backend implementation of this to be done in: https://github.com/BitcoinDevShop/pln/issues/22
frontend implementation of this to be done in: https://github.com/BitcoinDevShop/pln/issues/32
