### ISSUE TITLE
figure out what to do with money after channel close

### ISSUE THREAD

**Issue by futurepaul** [BitcoinDevShop/pln#45]
for now: warning, you should really coinjoin this. it's "not spendable" unless you're sending it to samourai / whirlpool.

**Comment by TonyGiorgio** [comment]
Have a UTXO list, each one of the UTXO's has to be sent out to an address. Complete amount, one at a time.

**Comment by TonyGiorgio** [comment]
Created separate tickets for listing the utxos and sending the utxos

https://github.com/BitcoinDevShop/pln/issues/52
https://github.com/BitcoinDevShop/pln/issues/51
https://github.com/BitcoinDevShop/pln/issues/57
https://github.com/BitcoinDevShop/pln/issues/56
