### ISSUE TITLE
Important security update.

### ISSUE THREAD

**Issue by abitcoinperson** [BitcoinDevShop/pln#75]
The Ben License:

May you do good and not evil

May you find forgiveness for yourself and forgive others

May you share freely, never taking more than you give

Assume nothing works, and you may be pleasantly surprised; and when it breaks, you get to keep both pieces.

I'm an idiot. 

![image](https://user-images.githubusercontent.com/8769819/187114320-068af063-16a6-40e9-92df-d56dd01acb58.jpeg)

**Comment by TonyGiorgio** [comment]
lol #wontfix
